/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BlindHireInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applicationCount"
      | "applications"
      | "applyForRole"
      | "candidateApplications"
      | "confidentialProtocolId"
      | "employerRoles"
      | "getCandidateApplications"
      | "getEmployerRoles"
      | "getMatchResult"
      | "postRole"
      | "roleCount"
      | "roles"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApplicationSubmitted"
      | "MatchComputed"
      | "RolePosted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "applicationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applications",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "applyForRole",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "candidateApplications",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "employerRoles",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidateApplications",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployerRoles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "postRole",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "roleCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "roles", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "applicationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyForRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "candidateApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "employerRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidateApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployerRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "postRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "roleCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "roles", data: BytesLike): Result;
}

export namespace ApplicationSubmittedEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    roleId: BigNumberish,
    candidate: AddressLike
  ];
  export type OutputTuple = [
    applicationId: bigint,
    roleId: bigint,
    candidate: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    roleId: bigint;
    candidate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchComputedEvent {
  export type InputTuple = [applicationId: BigNumberish];
  export type OutputTuple = [applicationId: bigint];
  export interface OutputObject {
    applicationId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RolePostedEvent {
  export type InputTuple = [roleId: BigNumberish, employer: AddressLike];
  export type OutputTuple = [roleId: bigint, employer: string];
  export interface OutputObject {
    roleId: bigint;
    employer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlindHire extends BaseContract {
  connect(runner?: ContractRunner | null): BlindHire;
  waitForDeployment(): Promise<this>;

  interface: BlindHireInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applicationCount: TypedContractMethod<[], [bigint], "view">;

  applications: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, boolean] & {
        candidate: string;
        roleId: bigint;
        matched: string;
        computed: boolean;
      }
    ],
    "view"
  >;

  applyForRole: TypedContractMethod<
    [
      roleId: BigNumberish,
      _years: BytesLike,
      _yearsProof: BytesLike,
      _score: BytesLike,
      _scoreProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  candidateApplications: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  employerRoles: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getCandidateApplications: TypedContractMethod<
    [candidate: AddressLike],
    [bigint[]],
    "view"
  >;

  getEmployerRoles: TypedContractMethod<
    [employer: AddressLike],
    [bigint[]],
    "view"
  >;

  getMatchResult: TypedContractMethod<[appId: BigNumberish], [string], "view">;

  postRole: TypedContractMethod<
    [
      _minYears: BytesLike,
      _minYearsProof: BytesLike,
      _minScore: BytesLike,
      _minScoreProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  roleCount: TypedContractMethod<[], [bigint], "view">;

  roles: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, boolean] & {
        employer: string;
        minYears: string;
        minScore: string;
        active: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applicationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "applications"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, boolean] & {
        candidate: string;
        roleId: bigint;
        matched: string;
        computed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "applyForRole"
  ): TypedContractMethod<
    [
      roleId: BigNumberish,
      _years: BytesLike,
      _yearsProof: BytesLike,
      _score: BytesLike,
      _scoreProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "candidateApplications"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "employerRoles"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCandidateApplications"
  ): TypedContractMethod<[candidate: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getEmployerRoles"
  ): TypedContractMethod<[employer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getMatchResult"
  ): TypedContractMethod<[appId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "postRole"
  ): TypedContractMethod<
    [
      _minYears: BytesLike,
      _minYearsProof: BytesLike,
      _minScore: BytesLike,
      _minScoreProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "roles"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, boolean] & {
        employer: string;
        minYears: string;
        minScore: string;
        active: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ApplicationSubmitted"
  ): TypedContractEvent<
    ApplicationSubmittedEvent.InputTuple,
    ApplicationSubmittedEvent.OutputTuple,
    ApplicationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "MatchComputed"
  ): TypedContractEvent<
    MatchComputedEvent.InputTuple,
    MatchComputedEvent.OutputTuple,
    MatchComputedEvent.OutputObject
  >;
  getEvent(
    key: "RolePosted"
  ): TypedContractEvent<
    RolePostedEvent.InputTuple,
    RolePostedEvent.OutputTuple,
    RolePostedEvent.OutputObject
  >;

  filters: {
    "ApplicationSubmitted(uint256,uint256,address)": TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;
    ApplicationSubmitted: TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;

    "MatchComputed(uint256)": TypedContractEvent<
      MatchComputedEvent.InputTuple,
      MatchComputedEvent.OutputTuple,
      MatchComputedEvent.OutputObject
    >;
    MatchComputed: TypedContractEvent<
      MatchComputedEvent.InputTuple,
      MatchComputedEvent.OutputTuple,
      MatchComputedEvent.OutputObject
    >;

    "RolePosted(uint256,address)": TypedContractEvent<
      RolePostedEvent.InputTuple,
      RolePostedEvent.OutputTuple,
      RolePostedEvent.OutputObject
    >;
    RolePosted: TypedContractEvent<
      RolePostedEvent.InputTuple,
      RolePostedEvent.OutputTuple,
      RolePostedEvent.OutputObject
    >;
  };
}
